# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-02 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlotXRay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite', models.CharField(choices=[('1', 'GOES 15'), ('2', 'GOES 16')], max_length=16)),
                ('band', models.CharField(choices=[('1', 'Soft X-Ray'), ('2', 'Hard X-Ray')], max_length=16)),
                ('flux_init', models.FloatField(blank=True, default=0.0, null=True)),
                ('flux_finish', models.FloatField(blank=True, default=10.0, null=True)),
                ('initial_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
